export const INIT = 'init'
export const SET_API_KEY = 'setApiKey'
export const SET_LOCATION = 'setLocation'
export const DELETE_RECENT_LOCATION = 'deleteRecentLocation'
export const SET_CALL_COUNT = 'setCallCount'
export const SET_WEATHER = 'setWeather'
